---
- name: Instalación de Apache y PHP para el equipo frontend
  hosts: frontend
  become: true

  tasks:
    - name: Inclusión de archivo de variables
      ansible.builtin.include_vars:
        ../vars/variables.yml

    - name: Actualización de los repositorios y de los programas instalados
      ansible.builtin.apt:
        update_cache: true
        upgrade: true

    - name: Instalación de servidor web Apache
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: Instalación de PHP y módulos de PHP para conectar con la base de datos y Apache
      ansible.builtin.apt:
        name: "{{ PHP_Packages }}"
        state: present

    - name: Copiado de template 000-default.conf.j2 al equipo remoto
      ansible.builtin.template:
        src: "{{ Template_000_default.Local_Source }}"
        dest: /etc/apache2/sites-available/000-default.conf
        mode: 0644

    - name: Copiado de template dir.conf.j2 al equipo remoto
      ansible.builtin.template:
        src: "{{ Template_dir.Local_Source }}"
        dest: /etc/apache2/mods-available/dir.conf
        mode: 0644

    - name: Habilitación del módulo rewrite de Apache
      community.general.apache2_module:
        name: rewrite
        state: present
      notify: Reiniciar servidor Apache

  handlers:
    - name: Reiniciar servidor Apache
      ansible.builtin.service:
        name: apache2
        state: restarted
