---
- name: Despliegue del balanceador de carga
  hosts: balancer
  become: true

  tasks:
    - name: Inclusión del archivo de variables
      ansible.builtin.include_vars:
        ../vars/variables.yml

    - name: Actualización de repositorios y programas instalados
      ansible.builtin.apt:
        update_cache: true
        upgrade: true

    - name: Instalación de Apache2
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: Habilitación de módulos para el balanceador de carga
      community.general.apache2_module:
        name: "{{ item }}"
        state: present
       with_items:
        - lbmethod_byrequests
        - proxy_html
        - proxy_connect
        - proxy_balancer
        - headers
        - deflate
        - rewrite
        - proxy_ajp
        - proxy_http
        - proxy

    - name: Copiado de template 000-default-balancer.conf.j2 al equipo remoto
      ansible.builtin.template:
        src: "{{ Balancer.Local_Source }}"
        dest: /etc/apache2/sites-available/000-default.conf
        mode: 0644
      notify: Reinicio de servidor Apache

  handlers:
    - name: Reinicio de servidor Apache
      ansible.builtin.service:
        name: apache2
        state: restarted
