---

#-----------------------------------------------------------------------------------------------
# Variables para la obtenci칩n del certificado de Let's Encrypt para TLS

Cerbot:
  Email: tetz_dqhwr17@yutep.com
  Domain: practicasiaw09jrrl.ddns.net


#-----------------------------------------------------------------------------------------------
# Variables para el archivo 000-default.conf

Template_000_default:
# Variable de ruta local del archivo
  Local_Source: ../templates/000-default.conf.j2

# Variable de cambio del contenido del archivo
  DocumentRoot: /var/www/html


#-----------------------------------------------------------------------------------------------
# Variables para el archivo dir.conf

Template_dir:
# Variable de ruta local del archivo
  Local_Source: ../templates/dir.conf.j2

# Variable de cambio del contenido del archivo
  Directory_index: DirectoryIndex index.php index.html index.cgi index.pl index.xhtml index.htm


#-----------------------------------------------------------------------------------------------
# Lista de paquetes de PHP para instalar

PHP_Packages:
  - php
  - libapache2-mod-php
  - php-mysql


#-----------------------------------------------------------------------------------------------
# Variables para establecer la base de datos, el usuario y su contrase침a y la localizaci칩n

Database:
  Name: wordpress_db
  User: wordpress_user
  Password: wordpress_pass
  Host: localhost


#-----------------------------------------------------------------------------------------------
# Variables para la personalizaci칩n de la URL de WordPress

WordPress:
  Home: https://practicasiaw09jrrl.ddns.net
  SiteURL: https://practicasiaw09jrrl.ddns.net/wordpress
