---

#------------------------------------------------------------------------------------------------------
# Variables para el balanceador de carga

Balancer:
  # Variable de ruta local del template 000-default-balancer.conf.j2
  Local_Source: ../templates/000-default-balancer.conf.j2

  # Variables de cambio del contenido del template 000-default-balancer.conf.j2
  IP_HTTP_Server_1: 172.31.77.79
  IP_HTTP_Server_2: 172.31.78.66

  # Variables para obtener el certificado de Let's Encrypt
  Certbot_Domain: practica09iawjrrl.ddns.net
  Certbot_Email: tetz_dqhwr17@yutep.com


#------------------------------------------------------------------------------------------------------
# Variables para los frontend

Frontend:

  # Variable de ruta local del template 000-default-frontend.conf.j2
  Local_Source_000: ../templates/000-default-frontend.conf.j2

  # Variable de cambio del contenido del template 000-default-frontend.conf.j2
  DocumentRoot: /var/www/html

  # Lista de paquetes de PHP para instalar
  PHP_Packages:
    - php
    - libapache2-mod-php
    - php-mysql

  # Variable de ruta local del template dir.conf.j2 
  Local_Source_dir: ../templates/dir.conf.j2

  # Variable de cambio del contenido del template dir.conf.j2
  Directory_index_dir: DirectoryIndex index.php index.html index.cgi index.pl index.xhtml index.htm


#------------------------------------------------------------------------------------------------------
# Variables para NFS Server

NFS_Server:
  # Variable de ruta local del template exports.j2
  Local_Source_exports: ../templates/exports.j2

  # Directorio a compartir por el servidor NFS para el template exports.j2
  Shared_directory_exports: /var/www/html

  # Variables de cambio del contenido del template exports.j2
  Range_AWS_Private_IP_exports: 172.31.0.0/16

  # Opciones para el servidor NFS del template exports.j2
  NFS_Options_exports: rw,sync,no_root_squash,no_subtree_check

  # Conexión con el servidor NFS para el montaje y el archivo fstab
  Private_IP_NFS_Server: 172.31.65.63


#------------------------------------------------------------------------------------------------------
# Variables para establecer la base de datos, el usuario y su contraseña y la localización

Backend_Database:
  Name: wordpress_db
  User: wordpress_user
  Password: wordpress_pass
  Host: 172.31.76.41


#------------------------------------------------------------------------------------------------------
# Variables para la personalización de la URL de WordPress

WordPress:
  # Personalización de la URL para no referenciar al directorio de instalación
  Home: https://practica09iawjrrl.ddns.net

  # Ruta interna de los archivos de WordPress
  SiteURL: https://practica09iawjrrl.ddns.net/wordpress
